/*****************************************************************************
 Copyright 2020-2023 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @defgroup grp_xcvr_fuji_common_imp FUJI Driver common Interface
    @ingroup grp_fuji_phy

    @addtogroup grp_xcvr_fuji_common_imp
    @{

    @file fuji_common.h
*/

#ifndef FUJI_COMMON_H
#define FUJI_COMMON_H

#include <xcvr_common.h>
#include <xcvr_extphy.h>
/**
    @name FUJI API IDs
    @{
    @brief API IDs for FUJI driver
*/
#define BRCM_SWARCH_FUJI_DEVADDR_TYPE                                (0x8100U) /**< @brief #FUJI_DevAddrType          */
#define BRCM_SWARCH_FUJI_CL45VEN_CORE_SHD18_REG_TYPE                 (0x8101U) /**< @brief #FUJI_CL45VEN_CORE_SHD18_REG_TYPE  */
#define BRCM_SWARCH_FUJI_CL45VEN_CORE_EXP35_REG_TYPE                 (0x8102U) /**< @brief #FUJI_CL45VEN_CORE_EXP35_REG_TYPE  */
#define BRCM_SWARCH_FUJI_CL45VEN_CORE_SHD1C_03_REG_TYPE              (0x8103U) /**< @brief #FUJI_CL45VEN_CORE_SHD1C_03_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_DSP_TAP14_REG_TYPE                  (0x8104U) /**< @brief #FUJI_CL45VEN_DSP_TAP14_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_DSP_TAP15_REG_TYPE                  (0x8105U) /**< @brief #FUJI_CL45VEN_DSP_TAP15_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_TYPE            (0x8106U) /**< @brief #FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_CORE_SHD18_000_REG_TYPE             (0x8107U) /**< @brief #FUJI_CL45VEN_CORE_SHD18_000_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_CORE_SHD18_100_REG_TYPE             (0x8108U) /**< @brief #FUJI_CL45VEN_CORE_SHD18_100_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_DSP_TAP10_REG_TYPE                  (0x8109U) /**< @brief #FUJI_CL45VEN_DSP_TAP10_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_DSP_TAP29_REG_TYPE                  (0x810AU) /**< @brief #FUJI_CL45VEN_DSP_TAP29_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_BR_EOC_EXP92_REG_TYPE               (0x810BU) /**< @brief #FUJI_CL45VEN_BR_EOC_EXP92_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_AFE_RXCONFIG_0_REG_TYPE         (0x810CU) /**< @brief #FUJI_CL45VEN_TOP_AFE_RXCONFIG_0_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_AFE_TXCONFIG_3_REG_TYPE         (0x810DU) /**< @brief #FUJI_CL45VEN_TOP_AFE_TXCONFIG_3_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_TYPE  (0x810EU) /**< @brief #FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_TYPE */
#define BRCM_SWARCH_FUJI_CHECK_ERR_MACRO                             (0x810FU) /**< @brief #FUJI_CHECK_ERR                                */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_TYPE    (0x8110U) /**< @brief #FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_TYPE */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_TYPE         (0x8111U) /**< @brief #FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_TYPE      */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_MISC_V1P8_DATA_REG_TYPE         (0x8112U) /**< @brief #FUJI_CL45VEN_TOP_MISC_V1P8_DATA_REG_TYPE      */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_TYPE     (0x8113U) /**< @brief #FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_TYPE  */
#define BRCM_SWARCH_FUJI_VTMON_TYPE                                  (0x8114U) /**< @brief #FUJI_VTMonType                                */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_TYPE       (0x8115U) /**< @brief #FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_TYPE    */
#define BRCM_SWARCH_FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_TYPE         (0x8116U) /**< @brief #FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_TYPE      */
/** @} */

/**
    @brief Return value Error check

    @trace #BRCM_SWREQ_FUJI
*/
#define FUJI_CHECK_ERR(ret, data)                                 \
    if ((BCM_ERR_OK != (ret))) {                                  \
        BCM_LOG_ERROR(0U, (uint32_t)BCM_STATE_READY, ret, data);  \
        return ret;}

/**
    @name FUJI_DevAddrType
    @{
    @brief CL45 port addresses

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint8_t FUJI_DevAddrType;
#define FUJI_DEVADDR_PMAPMD                     (1U)
#define FUJI_DEVADDR_PCS                        (3U)
#define FUJI_DEVADDR_AN                         (7U)
#define FUJI_DEVADDR_MISC                       (30U)
/** @} */


/**
    @name FUJI_VTMonType
    @{
    @brief Denali VTMON Temp and Volt macros

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_VTMonType;
#define FUJI_VTMON_TEMP_BIAS                 (41335000UL)
#define FUJI_VTMON_TEMP_PRESCALE             (49055UL)
#define FUJI_VTMON_TEMP_DIV                  (100000UL)
#define FUJI_VTMON_TEMP(aVal)                ((((int32_t)FUJI_VTMON_TEMP_BIAS - ((int32_t)(aVal) * (int32_t)FUJI_VTMON_TEMP_PRESCALE)) / (int32_t)FUJI_VTMON_TEMP_DIV))
#define FUJI_VTMON_TEMP_TOREG(aVal)          ((((int32_t)FUJI_VTMON_TEMP_BIAS - ((int32_t)(aVal) * (int32_t)FUJI_VTMON_TEMP_DIV)) / (int32_t)FUJI_VTMON_TEMP_PRESCALE))
#define FUJI_VTMON_V1P0_SCALE                (1227U)
#define FUJI_VTMON_V1P8_SCALE                (537U)
#define FUJI_VTMON_V3P3_2P5_SCALE            (1074U)
#define FUJI_VTMON_VOLTAGE_SHIFT             (10U)
#define FUJI_VTMON_VOLT_V1P0(aVal)           (((FUJI_VTMON_V1P0_SCALE * (aVal)) >> FUJI_VTMON_VOLTAGE_SHIFT))
#define FUJI_VTMON_VOLT_V1P0_TOREG(aVal)     (((uint16_t)((((uint32_t)aVal) << FUJI_VTMON_VOLTAGE_SHIFT)/ FUJI_VTMON_V1P0_SCALE)))
#define FUJI_VTMON_VOLT_V1P8(aVal)           (((FUJI_VTMON_V1P8_SCALE * (aVal)) >> FUJI_VTMON_VOLTAGE_SHIFT))
#define FUJI_VTMON_VOLT_V1P8_TOREG(aVal)     (((uint16_t)((((uint32_t)aVal) << FUJI_VTMON_VOLTAGE_SHIFT)/ FUJI_VTMON_V1P8_SCALE)))
#define FUJI_VTMON_VOLT_V3P3_2P5(aVal)       (((FUJI_VTMON_V3P3_2P5_SCALE * (aVal)) >> FUJI_VTMON_VOLTAGE_SHIFT))
#define FUJI_VTMON_VOLT_V3P3_2P5_TOREG(aVal) (((uint16_t)((((uint32_t)aVal) << FUJI_VTMON_VOLTAGE_SHIFT)/ FUJI_VTMON_V3P3_2P5_SCALE)))
/** @} */

/**
    @name FUJI_CL45VEN_CORE_SHD18_REG_TYPE
    @{
    @brief Miscellanous Control Register (Shadow Register Selector = "111")

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_CORE_SHD18_REG_TYPE;
#define FUJI_CL45VEN_CORE_SHD18_REG_CHIP_SGMII_MASK  (0x7167U)
#define FUJI_CL45VEN_CORE_SHD18_REG_CHIP_RGMII_MASK  (0x71E7U)
#define FUJI_CL45VEN_CORE_SHD18_REG_CHIP_INIT_MASK  (0x7067U)
#define FUJI_CL45VEN_CORE_SHD18_REG_SHD18_RDSEL_MASK  (0x7000U)
#define FUJI_CL45VEN_CORE_SHD18_REG_SHD18_RDSEL_SHIFT  (12U)
#define FUJI_CL45VEN_CORE_SHD18_REG_PKT_CNTR_MASK  (0x800U)
#define FUJI_CL45VEN_CORE_SHD18_REG_PKT_CNTR_SHIFT  (11U)
#define FUJI_CL45VEN_CORE_SHD18_REG_BYPASS_WIRESPEED_TIMER_MASK  (0x400U)
#define FUJI_CL45VEN_CORE_SHD18_REG_BYPASS_WIRESPEED_TIMER_SHIFT  (10U)
#define FUJI_CL45VEN_CORE_SHD18_REG_FORCE_AUTO_MDIX_MASK  (0x200U)
#define FUJI_CL45VEN_CORE_SHD18_REG_FORCE_AUTO_MDIX_SHIFT  (9U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_TIMING_MAS  (0x100U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_TIMING_SHIFT  (8U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_MASK  (0x80U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_SHIFT  (7U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_RXER_MASK  (0x40U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_RXER_SHIFT  (6U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_OB_STATUS_DIS_MASK  (0x20U)
#define FUJI_CL45VEN_CORE_SHD18_REG_RGMII_OB_STATUS_DIS_SHIFT  (5U)
#define FUJI_CL45VEN_CORE_SHD18_REG_WIRESPEED_EN_MASK  (0x10U)
#define FUJI_CL45VEN_CORE_SHD18_REG_WIRESPEED_EN_SHIFT  (4U)
#define FUJI_CL45VEN_CORE_SHD18_REG_MDIO_ALL_PHY_SEL_MASK  (0x8U)
#define FUJI_CL45VEN_CORE_SHD18_REG_MDIO_ALL_PHY_SEL_SHIFT  (3U)
#define FUJI_CL45VEN_CORE_SHD18_REG_SHD18_SEL_MASK  (0x7U)
#define FUJI_CL45VEN_CORE_SHD18_REG_SHD18_SEL_SHIFT  (0U)
#define FUJI_CL45VEN_CORE_SHD18_REG_CL45_ADDR  (0x902FU)
/** @} */


/**
    @name FUJI_CL45VEN_CORE_EXP35_REG_TYPE
    @{
    @brief Late Collision Counter Threshold Register

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_CORE_EXP35_REG_TYPE;
#define FUJI_CL45VEN_CORE_EXP35_REG_CHIP_INIT_MASK  (0x0000U)
#define FUJI_CL45VEN_CORE_EXP35_REG_MII_INTERFACE_MODES_MASK  (0xF00U)
#define FUJI_CL45VEN_CORE_EXP35_REG_MII_INTERFACE_MODES_SHIFT  (8U)
#define FUJI_CL45VEN_CORE_EXP35_REG_LATE_COL_CNTR_THD_MASK  (0xFFU)
#define FUJI_CL45VEN_CORE_EXP35_REG_LATE_COL_CNTR_THD_SHIFT  (0U)
#define FUJI_CL45VEN_CORE_EXP35_REG_CL45_ADDR  (0x9045)
/** @} */

/**
    @name FUJI_CL45VEN_CORE_SHD1C_03_REG_TYPE
    @{
    @brief Clock Alignment Control Regsiter (Shadow Register Selector = "03h")

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_CORE_SHD1C_03_REG_TYPE;
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_RGMII_MASK  (0x0E00U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_SHD1C_SEL_MASK  (0x7C00U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_SHD1C_SEL_SHIFT  (10U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_GTXCLK_DLY_EN_MASK  (0x200U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_GTXCLK_DLY_EN_SHIFT  (9U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_GMII_CLK_ALIGN_STRB_MASK  (0x100U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_GMII_CLK_ALIGN_STRB_SHIFT  (8U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_RXCLK_ALIGN_STRB_MASK  (0x80U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_RXCLK_ALIGN_STRB_SHIFT  (7U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_DLY_VALUE_MASK  (0x70U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_DLY_VALUE_SHIFT  (4U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_DLY_LINE_SEL_MASK  (0xFU)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_DLY_LINE_SEL_SHIFT  (0U)
#define FUJI_CL45VEN_CORE_SHD1C_03_REG_CL45_ADDR  (0x9013U)
/** @} */

/**
    @name FUJI_CL45VEN_DSP_TAP10_REG_TYPE
    @{
    @brief PLL Bandwidth Control/Status and Path Metric Reset Register (x1)

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_DSP_TAP10_REG_TYPE;
#define FUJI_CL45VEN_DSP_TAP10_REG_CHIP_INIT_MASK (0x0329U)
#define FUJI_CL45VEN_DSP_TAP10_REG_CL45_ADDR  (0x9125U)
/** @} */

/**
    @name FUJI_CL45VEN_DSP_TAP14_REG_TYPE
    @{
    @brief MSE Threshold Register #1 (x1)

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_DSP_TAP14_REG_TYPE;
#define FUJI_CL45VEN_DSP_TAP14_REG_CHIP_INIT_MASK (0x9B52U)
#define FUJI_CL45VEN_DSP_TAP14_REG_MSE_THD_1_LSB_MASK  (0xFF00U)
#define FUJI_CL45VEN_DSP_TAP14_REG_MSE_THD_1_LSB_SHIFT  (8U)
#define FUJI_CL45VEN_DSP_TAP14_REG_ENERGY_DET_THD_MASK  (0xFFU)
#define FUJI_CL45VEN_DSP_TAP14_REG_ENERGY_DET_THD_SHIFT  (0U)
#define FUJI_CL45VEN_DSP_TAP14_REG_CL45_ADDR  (0x912DU)
/** @} */

/**
    @name FUJI_CL45VEN_DSP_TAP15_REG_TYPE
    @{
    @brief MSE Threshold Register #2 (x1)

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_DSP_TAP15_REG_TYPE;
#define FUJI_CL45VEN_DSP_TAP15_REG_CHIP_INIT_MASK (0xA04DU)
#define FUJI_CL45VEN_DSP_TAP15_REG_MSE_THD_3_SEL_MASK  (0xC000U)
#define FUJI_CL45VEN_DSP_TAP15_REG_MSE_THD_3_SEL_SHIFT  (14U)
#define FUJI_CL45VEN_DSP_TAP15_REG_MSE_THD_2_MASK  (0x3FFCU)
#define FUJI_CL45VEN_DSP_TAP15_REG_MSE_THD_2_SHIFT  (2U)
#define FUJI_CL45VEN_DSP_TAP15_REG_MSE_THD_1_MSB_MASK  (0x3U)
#define FUJI_CL45VEN_DSP_TAP15_REG_MSE_THD_1_MSB_SHIFT  (0U)
#define FUJI_CL45VEN_DSP_TAP15_REG_CL45_ADDR  (0x912EU)
/** @} */

/**
    @name FUJI_CL45VEN_DSP_TAP29_REG_TYPE
    @{
    @brief Phy Control Force State/Timers/Alternate Behaviour Register #1 (x1)

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_DSP_TAP29_REG_TYPE;
#define FUJI_CL45VEN_DSP_TAP29_REG_CHIP_INIT_MASK (0x81C4U)
#define FUJI_CL45VEN_DSP_TAP29_REG_CL45_ADDR  (0x9154U)
/** @} */

/**
    @name FUJI_CL45VEN_BR_EOC_EXP92_REG_TYPE
    @{
    @brief BroadReach LRE Misc Control

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_BR_EOC_EXP92_REG_TYPE;
#define FUJI_CL45VEN_BR_EOC_EXP92_REG_CHIP_INIT_MASK (0x9A65U)
#define FUJI_CL45VEN_BR_EOC_EXP92_REG_CL45_ADDR  (0x9302U)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_AFE_RXCONFIG_0_REG_TYPE
    @{
    @brief RXCONFIG_0 Register

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_AFE_RXCONFIG_0_REG_TYPE;
#define FUJI_CL45VEN_TOP_AFE_RXCONFIG_0_REG_CHIP_INIT_MASK (0x3592U)
#define FUJI_CL45VEN_TOP_AFE_RXCONFIG_0_REG_CL45_ADDR  (0x91E0U)
/** @} */

/**
    @name CL45VEN_TOP_AFE_TXCONFIG_3_REG_TYPE
    @{
    @brief TXCONFIG_3 Register

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_AFE_TXCONFIG_3_REG_TYPE;
#define FUJI_CL45VEN_TOP_AFE_TXCONFIG_3_REG_CHIP_INIT_MASK (0x1800U)
#define FUJI_CL45VEN_TOP_AFE_TXCONFIG_3_REG_CL45_ADDR  (0x91F3U)
/** @} */

/**
    @name FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_TYPE
    @{
    @brief TC1 Dynamic Channel Quality - Signal Quality Index

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_TYPE;
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_SQI_MASK  (0xEU)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_SQI_SHIFT  (1U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_REG_CL45_ADDR  (0x9174U)
/** @} */

/**
    @name FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_TYPE
    @{
    @brief Signal Quality Threshold

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_TYPE;
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_0_MASK  (0x0309U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_0_CL45_ADDR  (0x9175U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_1_MASK  (0x0269U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_1_CL45_ADDR  (0x9176U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_2_MASK  (0x01EBU)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_2_CL45_ADDR  (0x9177U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_3_MASK  (0x0185U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_3_CL45_ADDR  (0x9178U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_4_MASK  (0x0135U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_4_CL45_ADDR  (0x9179U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_5_MASK  (0x00F1U)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_5_CL45_ADDR  (0x917AU)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_6_MASK  (0x00BFU)
#define FUJI_CL45VEN_DSP_TC1_DCQ_SQI_THRESHOLD_REG_6_CL45_ADDR  (0x917BU)
/** @} */

/**
    @name FUJI_CL45VEN_CORE_SHD18_000_REG_TYPE
    @{
    @brief Auxiliary Control Register (Shadow Register Selector = "000")

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_CORE_SHD18_000_REG_TYPE;
#define FUJI_CL45VEN_CORE_SHD18_000_REG_CHIP_INIT_MASK (0x0C30U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EXT_LPBK_MASK  (0x8000U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EXT_LPBK_SHIFT  (15U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EXT_PKT_LEN_MASK  (0x4000U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EXT_PKT_LEN_SHIFT  (14U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EDGERATE_CTL_1000T_MASK  (0x3000U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EDGERATE_CTL_1000T_SHIFT  (12U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_SM_DSP_CLK_EN_MASK  (0x800U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_SM_DSP_CLK_EN_SHIFT  (11U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_TX_6DB_CODING_MASK  (0x400U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_TX_6DB_CODING_SHIFT  (10U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_RCV_SLICING_MASK  (0x300U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_RCV_SLICING_SHIFT  (8U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_PRF_DIS_MASK  (0x80U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_PRF_DIS_SHIFT  (U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_INVERSE_PRF_DIS_MASK  (0x40U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_INVERSE_PRF_DIS_SHIFT  (6U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EDGERATE_CTL_100TX_MASK  (0x30U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_EDGERATE_CTL_100TX_SHIFT  (4U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_DIAGNOSTIC_MASK  (0x8U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_DIAGNOSTIC_SHIFT  (3U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_SHD18_SEL_MASK  (0x7U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_SHD18_SEL_SHIFT  (0U)
#define FUJI_CL45VEN_CORE_SHD18_000_REG_CL45_ADDR  (0x9028U)
/** @} */

/**
    @name FUJI_CL45VEN_CORE_SHD18_100_REG_TYPE
    @{
    @brief Auxiliary Control Register (Shadow Register Selector = "000")

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_CORE_SHD18_100_REG_TYPE;
#define FUJI_CL45VEN_CORE_SHD18_100_REG_RMT_LPBK_EN_MASK  (0x8000U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_RMT_LPBK_EN_SHIFT  (15U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_TDK_FIX_EN_MASK  (0x4000U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_TDK_FIX_EN_SHIFT  (14U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_DLL_BYPASS_CLK_MASK  (0x2000U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_DLL_BYPASS_CLK_SHIFT  (13U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BLOCK_10BT_RESTART_AUTONEG_MASK  (0x1000U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BLOCK_10BT_RESTART_AUTONEG_SHIFT  (12U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_RMT_LPBK_TRISTATE_MASK  (0x800U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_RMT_LPBK_TRISTATE_SHIFT  (11U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_WAKEUP_MASK  (0x400U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_WAKEUP_SHIFT  (10U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_POLARITY_BYPASS_MASK  (0x200U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_POLARITY_BYPASS_SHIFT  (9U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_IDLE_BYPASS_MASK  (0x100U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_IDLE_BYPASS_SHIFT  (8U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_CLK_RESET_EN_MASK  (0x80U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_CLK_RESET_EN_SHIFT  (7U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_BYPASS_ADC_MASK  (0x40U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_BYPASS_ADC_SHIFT  (6U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_BYPASS_CRS_MASK  (0x20U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_BT_BYPASS_CRS_SHIFT  (5U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_SWAP_RXMDIX_MASK  (0x10U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_SWAP_RXMDIX_SHIFT  (4U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_HALFOUT_MASK  (0x8U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_HALFOUT_SHIFT  (3U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_SHD18_SEL_MASK  (0x7U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_SHD18_SEL_SHIFT  (0U)
#define FUJI_CL45VEN_CORE_SHD18_100_REG_CL45_ADDR  (0x902CU)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_TYPE
    @{
    @brief SGMII top control

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_TYPE;
#define FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_SGMII_MODE_MASK  (0x200U)
#define FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_SGMII_MODE_SHIFT  (9U)
#define FUJI_CL45VEN_TOP_MISC_SGMII_TOP_CTRL_REG_CL45_ADDR  (0x98B3U)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_TYPE
    @{
    @brief VTMON Control Register

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_TYPE;
#define FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_VTMON_SEL_MASK (0xEU)
#define FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_VTMON_SEL_VTMON_ALL_MON_MASK (0x4U)
#define FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_VTMON_SEL_SHIFT (1U)
#define FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_PWRDN_MASK (0x1U)
#define FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_PWRDN_SHIFT (0U)
#define FUJI_CL45VEN_TOP_MISC_VTMON_CNTRL_REG_CL45_ADDR (0x9831U)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_TYPE
    @{
    @brief Temperature Monitor Value

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_TYPE;
#define FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_VTMON_PHY_PWRDN_STS_MASK (0x8000U)
#define FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_VTMON_PHY_PWRDN_STS_SHIFT (15U)
#define FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_TEMP_DATA_MASK (0x3FFU)
#define FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_TEMP_DATA_SHIFT (0U)
#define FUJI_CL45VEN_TOP_MISC_TEMP_DATA_REG_CL45_ADDR (0x9832U)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_TYPE
    @{
    @brief Voltage Monitor 1.0V Value

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_TYPE;
#define FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_V1P0_DATA_MASK (0x7FFU)
#define FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_V1P0_DATA_SHIFT (0U)
#define FUJI_CL45VEN_TOP_MISC_V1P0_DATA_REG_CL45_ADDR (0x9835U)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_MISC_V1P8_DATA_REG_TYPE
    @{
    @brief Voltage Monitor 1.8V Value

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_MISC_V1P8_DATA_REG_TYPE;
#define FUJI_CL45VEN_TOP_MISC_V1P8_DATA_REG_V1P8_DATA_MASK (0xFFFU)
#define FUJI_CL45VEN_TOP_MISC_V1P8_DATA_REG_CL45_ADDR (0x983CU)
/** @} */

/**
    @name FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_TYPE
    @{
    @brief Voltage Monitor 3.3V/2.5V Value

    @trace #BRCM_SWREQ_FUJI
*/
typedef uint16_t FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_TYPE;
#define FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_V3P3_2P5_DATA_MASK (0xFFFU)
#define FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_V3P3_2P5_DATA_SHIFT (0U)
#define FUJI_CL45VEN_TOP_MISC_V3P3_2P5_DATA_REG_CL45_ADDR (0x9838U)
/** @} */

#endif /* FUJI_COMMON_H */

/** @} */
